[package]
name = "steamaudio-sys"
version = "0.0.0"
authors = ["Valaphee <iam@valaphee.com>"]
description = "Steam Audio bindings for Rust"
repository = "https://github.com/valaphee/steamaudio.git"
license = "Apache-2.0"

[build-dependencies]
bindgen = "0.65.1"
